name: intent
description: A simple to use Flutter plugin to deal with Android Intents - your one-stop-solution for Android Intents.
version: 1.4.0
homepage: https://github.com/itzmeanjan/intent

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: any

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: io.github.itzmeanjan.intent
        pluginClass: IntentPlugin
      ios:
        pluginClass: IntentPlugin
